[package]
name = "do-not-publish/not-for-publish"
version = "0.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
msgpack-luau = "cipharius/msgpack-luau@0.3.0"
luau-json = "seaofvoices/luau-json@0.1.1"
base64 = "reselim/base64@3.0.0"
