[package]
name = "caveful-games/xtruct"
version = "0.1.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "AGPL-3.0"

[dependencies]
msgpack-luau = "cipharius/msgpack-luau@0.3.0"
crc16 = "caveful-games/crc16@0.1.0"
