[package]
name = "caveful-games/rbxzstd"
version = "0.1.5"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"

[dependencies]
json = "seaofvoices/luau-json@0.1.1"
base64 = "reselim/base64@3.0.0"
